version: "3.8"

services:
  web:
    container_name: encode
    build: .
    ports:
      - "5000:3000"
    depends_on:
      - mongo

  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27018:27017"
